def make_meaningful(line, comment: str = '#'): ...
def next_line(f, comment: str = '#'): ...
def form_lines(*args): ...
def abs_fname(fname): ...
def expand_tabs(fname, overwrite: bool = True, tab_expand: int = 2) -> None: ...
def dict_to_spline(spline_dictionary): ...
