from _typeshed import Incomplete

def load(fname): ...
def read_solution(fname, reference_nurbs): ...
def dof_mapping(spline): ...
def export_cartesian(
    fname, spline_list, tolerance: Incomplete | None = None
): ...
def export(fname, nurbs, precision: int = 10): ...
