from splinepy._base import SplinepyBase as _SplinepyBase

class TileBase(_SplinepyBase):
    def __init__(self) -> None: ...
    @property
    def evaluation_points(self): ...
    @property
    def dim(self): ...
    @property
    def para_dim(self): ...
    def check_params(self, params): ...
    def check_param_derivatives(self, derivatives): ...
