from _typeshed import Incomplete

def configure(
    debug: bool = False, logfile: Incomplete | None = None
) -> None: ...
def debug(*log) -> None: ...
def info(*log) -> None: ...
def warning(*log) -> None: ...
def prepend_log(message, log_func): ...
