def valid_queries(spline, queries): ...
def clamped_knot_vectors(spline, warning: bool = True): ...

class Checker:
    def __init__(self, spl) -> None: ...
    def valid_queries(self, queries): ...
    def clamped_knot_vectors(self, warning: bool = True): ...
