from _typeshed import Incomplete
from splinepy._base import SplinepyBase as _SplinepyBase

class FFD(_SplinepyBase):
    def __init__(self, mesh: Incomplete | None = None, spline: Incomplete | None = None, padding: Incomplete | None = None) -> None: ...
    @property
    def mesh(self): ...
    @mesh.setter
    def mesh(self, mesh) -> None: ...
    @property
    def spline(self): ...
    @spline.setter
    def spline(self, spline) -> None: ...
    @property
    def padding(self): ...
    @padding.setter
    def padding(self, padding) -> None: ...
    def show(self, **kwargs): ...
    def showable(self, **kwargs): ...
