from _typeshed import Incomplete

def volume(spline, orders: Incomplete | None = None): ...
def parametric_function(spline, function, orders: Incomplete | None = None): ...
def physical_function(function, orders) -> None: ...

class Integrator:
    def __init__(self, spl) -> None: ...
    def volume(self, *args, **kwargs): ...
    def parametric_function(self, *args, **kwargs): ...
