from gustaf.helpers import options as _options

class SplineShowOption(_options.ShowOption):
    def __init__(self, helpee) -> None: ...

class MultipatchShowOption(_options.ShowOption):
    def __init__(self, helpee) -> None: ...

def make_showable(spline): ...
def show(spline, **kwargs): ...
