extern "C" {
void slsqp(int* m,
           int* meg,
           int* la,
           int* n,
           double* x,
           double* xl,
           double* xu,
           double* f,
           double* c,
           double* g,
           double* a,
           double* acc,
           int* iter,
           int* mode,
           double* w,
           int* l_w,
           int* jw,
           int* l_jw,
           double* alpha,
           double* f0,
           double* gs,
           double* h1,
           double* h2,
           double* h3,
           double* h4,
           double* t,
           double* t0,
           double* tol,
           int* iexact,
           int* incons,
           int* ireset,
           int* itermx,
           int* line,
           int* n1,
           int* n2,
           int* n3);
} /* extern "C */
