name: Test build on windows

on:
  push

permissions:
  contents: read

jobs:
  build_and_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11", "3.12"]
        os: [windows-latest]


    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up  ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install rtools (mingw-w64)
      run: |
        choco install rtools -y --no-progress --force --version=4.0.0.20220206
        echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH


    - name: install dependencies
      run: pip install numpy

    - name: build windows
      run: |
        pip install ".[test]" -v --config-settings=cmake.args="-DSPLINEPY_MORE=OFF"

    - name: test
      run: |
        pytest tests
